JOB_ARRIVAL = "uniform"
JOB_DISTRIBUTION = "uniform"
BW_PER_NODE = 10
RANDOM_SEED = 9973
MEM_PER_NODE = 48
POISSON_LAMBDA = 3
CPU_PER_NODE = 16
GPU_PER_NODE = 2
TOT_NUM_JOBS = 60
T = 20
JOB_SCHEDULER = "UTIL"
LOG_LEVEL = "ERROR"
MIN_SLEEP_UNIT = 10**-3

TS_INTERVAL = 600
DEFAULT_NUM_PS = 1
DEFAULT_NUM_WORKER = 1

# cluster node ips
NODE_LIST = ['1.1.1.1', '2.2.2.2']
LOSS_LITTLE_CHANGE_EPOCH_NUM = 10
LOSS_CONVERGENCE = 0.05